services:
  postgres:
    image: postgres:16
    container_name: events-postgres
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U events"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: events-rabbitmq
    ports:
      - "5672:5672"   # Puerto AMQP
      - "15672:15672" # Puerto Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: events-api:local
    container_name: events-api
    ports:
      - "5000:8080"
      - "5001:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EventsDb=Host=postgres;Port=5432;Database=events;Username=events;Password=events
      - MessageBroker__Host=rabbitmq
      - MessageBroker__Exchange=eventos.domain.events
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      # Azurite dentro de la red de Compose
      - BlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNoGV8X8kGq1p3RDYJ3CqgYh5hGd3clj3o==;BlobEndpoint=http://azurite:10000/devstoreaccount1
      - BlobStorage__Container=eventos-media
      - BlobStorage__PublicBaseUrl=http://azurite:10000/devstoreaccount1/eventos-media
    depends_on:
      - postgres
      - rabbitmq
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: events-azurite
    command: "azurite-blob --blobHost 0.0.0.0 --location /data --debug /data/debug.log"
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  azurite_data:
